RoaringBitmap/CRoaring

src/roaring.c
A minor fix for in_place or, length2 was getting compared twice.
=> Fixed issue with checking length of incorrect bitmap

include/containers/array.h, include/containers/bitset.h, include/containers/containers.h, include/roaring.h, src/containers/array.c, src/containers/bitset.c, src/roaring.c, tests/toplevel_unit.c
This pull request implements the following function:
```c
roaring_bitmap_t *roaring_bitmap_from_range(uint32_t min, uint32_t max, uint32_t step);
```
It creates a bitmap with values in `[min, min+step, min+2*step, ..., min+k*step]` such that `k*step<max` and `(k+1)*step>=max` (similar to what does the Python `range`).
To do this efficiently, two tricks are used:
* When the container is an array, we first construct an empty array allocated with the required size, then we append all the values.
* When the container is a bitset and `step` is a divisor of 64, all the cells of the bitsets are the same, so we just compute it once.
For `min=0, max=1000000000, step=1`, we get a speedup of about 200 with this solution, in comparison with the naive idea to use `roaring_bitmap_add` for every value …
=> Bitmap constructor from a range

src/roaring.c, tests/toplevel_unit.c
The container was freed twice: in `roaring_bitmap_remove` and in `ra_remove_at_index`.
The double free was crashing the program with the simple test I added.
I also think there was a typo in `test_remove_from_copies_false`, I fixed it.
=> Fix roaring_bitmap_remove by avoiding a double free.

include/containers/array.h, include/containers/bitset.h, include/containers/containers.h, include/containers/run.h, include/roaring.h, src/containers/bitset.c, src/containers/run.c, src/roaring.c, tests/CMakeLists.txt, tests/array_container_unit.c, tests/bitset_container_unit.c, tests/run_container_unit.c, tests/toplevel_unit.c
The goal here is to add this function:
```c
bool roaring_bitmap_get_element_of_rank(roaring_bitmap_t *ra, uint32_t rank, uint32_t *element);
```
It retrieves an element of given rank in the roaring bitmap.
To do so, we simply iterate on all the containers until we find the desired rank (or we reach the end if the rank is greater than the bitmap's size).
Some factorization of the code could be made, particularly in the tests. For instance, we could have a function returning a randomly generated bitmap. We could also factorize the code for some container tests into a generic file (e.g. `container_unit.c`).
But I think this should be the object of an other pull request.
Future work regarding rank queries can be:
* Implement rank range queries (e.g. to get a new bitmap containing all the …
=> Implement get_element_of_rank.

include/portability.h
This fixes the compilation on an old system.
=> Add UINT64_C and UINT32_C definitions to fix portability issues.

src/roaring.c, tests/toplevel_unit.c
The method `roaring_bitmap_flip_inplace` was causing a segmenntation fault when
a container of the bitmap had to be removed. It was due to a double free.
This PR fixes this by replacing two calls to `ra_remove_at_index_and_free` by calls
to `ra_remove_at_index`, in file `roaring.c`.
According to the tests, it does not introduce any memory leak, but we should check
carefully.
=> Fix flip_inplace by removing a double free.

include/roaring/portability.h
Needed by Microsoft CodeGen for `_aligned_malloc` as per #46
=> Included malloc.h in portability.h

amalgamation.sh, include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, include/roaring/containers/mixed_subset.h, include/roaring/containers/run.h, include/roaring/roaring.h, src/CMakeLists.txt, src/containers/array.c, src/containers/bitset.c, src/containers/mixed_subset.c, src/containers/run.c, src/roaring.c, tests/CMakeLists.txt, tests/container_comparison_unit.c, tests/toplevel_unit.c
The main contribution of this pull request is the addition of the two functions: 
```c
/**
* Return true if all the elements of ra1 are also in ra2.
*/
bool roaring_bitmap_is_subset(roaring_bitmap_t *ra1, roaring_bitmap_t *ra2);
/**
* Return true if all the elements of ra1 are also in ra2 and ra2 is strictly greater
* than ra1.
*/
bool roaring_bitmap_is_strict_subset(roaring_bitmap_t *ra1, roaring_bitmap_t *ra2);
```
They are implemented following the same spirit than `roaring_bitmap_equals`:
* The function `roaring_bitmap_is_subset` iterates on the containers of the two bitmaps. When two containers have a same key, they are compared.
* The comparison of these two containers is done in the generic function `container_is_subset`. It calls the right function according to the type of the two …
=> Implement is_subset function, close #55

src/roaring.c
When one of the two bitmaps is empty, the functions return the other bitmap, so we should not allocate a new one.
=> Fix memory leak in roaring_bitmap_or and roaring_bitmap_xor.

amalgamation.sh, cpp/roaring.hh, include/roaring/containers/array.h, include/roaring/containers/run.h
Including the C++ amalgamation in multiple compilation units causes some linker errors due to a few missing "inline"s.
=> Made changes allowing headers to be included in multiple compilation units

AUTHORS, amalgamation.sh, cpp/roaring64map.hh, include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, include/roaring/containers/run.h, include/roaring/roaring.h, include/roaring/roaring_types.h, src/containers/array.c, src/containers/bitset.c, src/containers/run.c, src/roaring.c, tests/cpp_unit.cpp
a 64-bit C++ implementation using the TreeMap methodology described in the http://r-libre.teluq.ca/930/1/Roaring64bits.pdf paper.
=> Added 64-bit C++ version using std::map for the high-order bits

cpp/roaring64map.hh, include/roaring/portability.h, src/containers/array.c, src/containers/bitset.c, src/containers/run.c, src/roaring.c, src/roaring_array.c, src/roaring_priority_queue.c, tests/cpp_unit.cpp
* fixed select in roaring64map.hh not returning the upper 32 bits
* fixed some incorrect printf format specifiers
* made an impossible brance of an if possible
* made compilation possible with DISABLE_X64 on MSVC 14.0
* TODO: tests and benchmarks and ABM optmizations
* removed .c file inline keyword
=> handful of bug fixes

README.md, cpp/roaring.hh, cpp/roaring64map.hh, include/roaring/roaring.h, include/roaring/roaring_array.h, src/roaring.c
changed the pointer to a CRoaring object inside of the C++ class into the object itself,
avoiding a malloc and free in the constructor/destructor,
this makes little difference to the 32-bit C++ class but speeds up adds to the 64-bit class by a few percent,
also did a few minor things
Bug fix:
C++ iterators now stop at max uint32_t instead of comparing equal to the end iterator at this point
Performance:
removed virtual keyword for C++ iterator class's destructor since it will cause most compilers
to generate a vtable for each object, bloating it up
(the lack of the keyword is safe in this case unless a user subclasses the iterator
and that subclass is deleted through a pointer with the type of the base class)
Feature:
added a toString member function to the C++ classes which makes STL …
=> Embedded C object inside C++ object

cpp/roaring64map.hh, include/roaring/bitset_util.h, include/roaring/containers/bitset.h, src/array_util.c, src/bitset_util.c, src/containers/array.c, src/containers/bitset.c, src/containers/convert.c, src/containers/mixed_andnot.c, src/containers/mixed_equal.c, src/containers/mixed_negation.c, src/containers/mixed_subset.c, src/containers/mixed_union.c, src/containers/mixed_xor.c, src/roaring_array.c, src/roaring_priority_queue.c
"Roaring" should not refer to the amount of warning text generated. This fixes a number of the warnings about code style (and one real bug) which are generated by Visual Studio on the default warning level. Note that this isn't quite all of them, only those in the path of my application.
=> made Visual Studio's warnings quieter the hard way

cpp/roaring64map.hh
A few bugs discovered when making heavy use of the 64-bit containers.
=> Fixed some bugs in the 64-bit layer

cpp/roaring64map.hh, tests/cpp_unit.cpp
With this update I'm changing to an on-disk format for 64-bit maps that doesn't store the size of the interior Roarings.
This is what I wanted to do originally by modifying the C API to return the amount of bytes read but I noticed I could achieve the same thing by using getSizeInBytes() after retrieval of each Roaring.
Note that although this breaks compatibility with old serialized maps, I think it's less of an issue since the getSizeInBytes() bug made it difficult to serialize in the first place!
Also if the C API was ever changed to return the bytes read, there would be no further need to modify the on-disk format. I think it is here to stay.
=> addressed getSizeInBytes() bug and made serialized 64-bit maps simpler

cpp/roaring64map.hh
Get ready for something very minute:
So there exists a category of STL iterators called "singular" in the C++ standard. It is illegal to copy construct from (or do anything except reassign to) these iterators. The most common way to end up with one of these iterators is through a default iterator constructor but you'll get one if you delete the container to which an iterator originally pointed.
So the Roaring64MapSetBitForwardIterator contains two STL iterators that can become singular through deletion of the Roaring64Map they referred to. When this happens it is technically no longer legal to copy the Roaring64MapSetBitForwardIterator. This means the static iterator in Roaring64Map::end() eventually, over the coarse of a longer program, becomes uncopiable when the first Roaring64Map to …
=> removed optimization on 64 bit map iterator due to standard non-compliance

include/roaring/bitset_util.h
Prevents compile errors with `-Wsign-compare` enabled. This is what I'm getting with Rust while trying to merge https://github.com/saulius/croaring-rs/pull/24:
```
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "../croaring-sys/CRoaring" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-lim
its" "-o" "/Users/sg/repos/croaring-rs/systest/target/debug/build/systest-90d26495522f312e/out/all.o" "-c" "/Users/sg/repos/croaring-rs/systest/target/debug/build/systest-90d2649
5522f312e/out/all.c"
cargo:warning=In file included from /Users/sg/repos/croaring-rs/systest/target/debug/build/systest-90d26495522f312e/out/all.c:3:
cargo:warning=../croaring-sys/CRoaring/roaring.h:625:19: error: comparison of integers of different signs: 'int' and 'uint32_t' …
```
=> Use comparable types in bitset util functions

include/roaring/bitset_util.h
There was a bug when testing the intersection between a bitset and a run container with only one run.
For example, this test was failing:
```c
void test_intersect_small_run_bitset() {
roaring_bitmap_t *rb1 = roaring_bitmap_from_range(0, 1, 1);
roaring_bitmap_t *rb2 = roaring_bitmap_from_range(1, 8194, 2);
assert_false(roaring_bitmap_intersect(rb1, rb2));
roaring_bitmap_free(rb1);
roaring_bitmap_free(rb2);
}
```
I did not add this piece of code in the test suite of CRoaring, because more extensive tests may be better.
=> Fix roaring_bitmap_intersect.

src/roaring.c, tests/toplevel_unit.c
When the length of one of the bitmaps was 0, then the bitmap created by `roaring_bitmap_create_with_capacity` was never freed nor returned.
=> Fix memory leak in roaring_bitmap_or_many.

src/containers/bitset.c
As there's no aligned_calloc(), which would allow to eliminate memset() that's more expensive the only way to optimize is use memset() still, but remove unneeded calloc() calls.
This should fix #65
=> Eliminate unneeded calloc() calls

include/roaring/portability.h
On FreeBSD 11 the compilation fails with:
```
/usr/include/malloc.h:3:2: error: "<malloc.h> has been
replaced by <stdlib.h>"
```
This PR disables including `malloc.h` on FreeBSD, which makes `make` and `make test` succeed.
=> Disables including malloc.h on FreeBSD, where it doesn't exist

src/roaring.c, tests/toplevel_unit.c
Range [0, 2^32) caused integer overflow and infinite loop.
=> Fixed infinite loop in roaring_bitmap_from_range()

CMakeLists.txt, README.md
Add -DENABLE_ROARING_TESTS=OFF to build only libroaring.a
which plays nicely with larger cmake projects that only want to build
and test their own projects tests.
Example run:
cmake -DENABLE_ROARING_TESTS=OFF -DBUILD_STATIC=ON ..
make -j8
Scanning dependencies of target roaring
[  5%] Building C object src/CMakeFiles/roaring.dir/containers/array.c.o
[ 11%] Building C object src/CMakeFiles/roaring.dir/array_util.c.o
[ 16%] Building C object src/CMakeFiles/roaring.dir/bitset_util.c.o
[ 27%] Building C object src/CMakeFiles/roaring.dir/containers/bitset.c.o
[ 27%] Building C object src/CMakeFiles/roaring.dir/containers/containers.c.o
[ 33%] Building C object src/CMakeFiles/roaring.dir/containers/convert.c.o
[ 38%] Building C object src/CMakeFiles/roaring.dir/containers/mixed_intersection.c.o …
=> cmake: Add cmake macros for inclusion into larger cmake projects

src/roaring_array.c
After calling ra_clear the state of roaring_array_t may be not correct and this can break the usage of other functions on the cleared array.
ra_clear already resets all pointers to NULL, it is safer to reset also `size` and `allocation_size` to zero.
It is then possible to call other functions on the cleared array without any risk.
=> fix ra_clear, it should reset size and allocated size

src/roaring_array.c
=> Use appropriate int32_t, not size_t, with realloc_array()

src/roaring.c
Sorry, I should have ensured the 32bit build was completely successful before the last pull.  After this, it is.
I'm not sure whether it's worthwhile to check that `sizeasarray` would fit into a `size_t` and fail somehow if not; I couldn't see any defined way to return an error.  It's highly unlikely that such a thing could be possible, I suspect.
=> Avoid warnings when sizeof(size_t) < sizeof(uint64_t)

include/roaring/portability.h
If we use inline functions then compile with /Ob0 (disable inline), as
many debug builds will do, this method will no longer have its
intended effect since the __assume(0) will be hidden inside the (not
inlined) function.
=> Windows: Use #define for __builtin_unreachable()

include/roaring/containers/array.h, include/roaring/containers/containers.h, src/containers/array.c, src/containers/mixed_andnot.c, src/containers/mixed_intersection.c, src/containers/mixed_union.c, src/roaring_array.c, tests/array_container_unit.c
array_container_add(): check that array must be converted to bitset
_before_ adding value, not after. This allows to limit array capacity
with DEFAULT_MAX_SIZE most of the time.
array.c: do not allocate space for more than DEFAULT_MAX_SIZE values
(soft limit, which can be exceeded in negation and some pairwise
operations; in this case we try to limit capacity with 64K)
roaring_array.c: do not allocate space for more than MAX_CONTAINERS
=> Improvements to allocation policy of array structs

CMakeLists.txt, README.md, tools/cmake/FindOptions.cmake
As outlined in https://github.com/RoaringBitmap/CRoaring/issues/176 ,
passing `march=native` can cause SIGILL when the build server is newer
than the server running the binary.
Currently, the only way around this issue is to use
`ROARING_DISABLE_NATIVE` and not use `march` at all.
This commit gives users additional control by adding a new CMake build
option to specify the architecture, e.g. `-DROARING_ARCH=westmere`.
If the existing `ROARING_DISABLE_NATIVE` flag is set to `OFF`, then
this new option has no effect.
=> Add ROARING_ARCH build option to control march=

include/roaring/portability.h
POPCNT support was not available on processors until around the time of SSE4.2 instructions. CRoaring flag for SSE4 guarantees POPCNT support. This patch uses that flag to guard against attempted usage
of the popcnt instruction on builds where we have not enabled that level of processor support. A software implentation is provided that should provide good all around performance.
=> Software implementation of popcnt

cpp/roaring.hh, include/roaring/roaring.h, src/roaring.c, tests/toplevel_unit.c
Noteable changes:
- `in_run_index` removed from the `roaring_uint32_iterator_t` which
breaks abi compatability. Just use the iterator's current value to
and `run_index` figure out if it should advance or not
- added invariant to `roaring_uint32_iterator_t`: the `container_index`
can be -1 in addition to `>= parent->high_low_container.size`.
Previously when the `container_index >= parent->high_low_container_size`
this represented that the iterator pointed past the end of the
container. This is still true, however -1 now indicates that the
iterator points before any of the values in container
- add `roaring_previous_uint32_iterator` method, which moves the
iterator backwards
- add `roaring_init_iterator_last` method, which initializes the
iterator to point to the last element in the bitmap …
=> Implement backward iterator

cpp/roaring.hh, cpp/roaring64map.hh, include/roaring/roaring_array.h, src/roaring.c, src/roaring_array.c, tests/cpp_unit.cpp
- Change `bool ra_init()` to `void ra_init()`, initializes array to have
zero capacity. Does not `malloc` and cannot fail. ABI breaking change
- Have `Roaring` ctor use new `ra_init()`
- Make `Roaring` move ctor and move assignment `noexcept`. This is important
for performance when holding them in stl containers (avoids copying)
- Delete dtor, copy ctor, move ctor, copy assignment operator and move
assignment operator for `RoaringSetBitForwardIterator` and `Roaring64Map`
since these objects don't manage any lifetimes manually. The compiler
provides these by _default_ to us
- Add `static_assert`s that C++ classes are `noexcept` moveable in cpp
unit test file
=> Have C++ defaults behave like stl defaults

include/roaring/containers/run.h
It appears in this code that under msvc, the sum of two uint16_t's is being promoted to a signed value. This change makes the promotionof each value explicitly to uint32_t to match the type of the comparison. Also, parentheses added to promote readability.
=> Resolve signed/unsigned comparison warning

include/roaring/portability.h, src/containers/bitset.c, tests/toplevel_unit.c
[#211] I verified that this solution works for my very specific name collision with another library. `make && make test` passes as well.
=> rename aligned_malloc, aligned_free

CMakeLists.txt, roaring.pc.in
This provides a way for dependent projects with non-CMake build
systems to locate libroaring. Multiple build systems can read these
files, either directly (like Meson) or via the pkg-config or pkgconf
tools (like Autotools).
=> Generate and install pkg-config metadata

amalgamation.sh, src/license-comment.h
This hopefully makes it easier for projects that embed a copy of the
amalgamated source code to remain in compliance with section 4 of the
terms of the Apache license.
=> Add copyright and licensing information to amalgamated source code

include/roaring/portability.h
These functions in portability.h are defined `static inline`:
__builtin_ctzll
__builtin_clzll
__builtin_popcountll
But with C++17 in Visual C++ 2019 (Visual Studio 16.7.3) this causes:
warning C4211: nonstandard extension used: redefined extern to static
Removing the `static` allows it to compile.
For an example of another project making such a patch, see e.g. the
Ethereum hash code:
https://github.com/chfast/ethash/pull/156/files
https://github.com/chfast/ethash/issues/154
=> Remove inline from wrappers for VS built-ins

include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, include/roaring/containers/run.h, src/containers/array.c, src/containers/bitset.c, src/containers/containers.c, src/containers/run.c, src/roaring_array.c, tests/toplevel_unit.c
There is code present in the library for container serialization
that is not reachable through the API.  This code is tied to the
`container_serialize()` and `container_deserialize()` functions,
which dispatch to functions for each specific container.  The
active serialization code paths are based on _write() and _read()
dispatch functions.
The only current usage of these functions was in a test of the `run`
container serialization in toplevel_unit.c.  This commit changes
that test so that it still generates a lower-level run container,
but then injects it into a single-container roaring_bitmap_t.  Then
it uses the active serialize and deserialize functions on that
bitmap in the test--effectively making it test deployed API code.
With that change in place, the following routines can be …
=> Remove unreachable serialization code

src/roaring.c
roaring_bitmap_select() has a `uint16_t` key, which gets shifted:
*element |= (key << 16);
For this operation, key is promoted to a signed int.  If the value
is large (e.g. 65535) then this particular left shift of 16 could
shift a 1 into the sign bit, which is undefined behavior:
https://stackoverflow.com/q/55066827/why-cant-you-shift-a-uint16-t
Change is to cast the key to `uint32_t` before shifting.
=> Cast uint16_t key to uint32_t in select

cpp/roaring.hh, tests/CMakeLists.txt, tests/cpp_random_unit.cpp, tests/roaring_checked.hh
Adds code to the Roaring C++ class under #ifdef ROARING_DOUBLECHECK_CPP
which maintains a parallel state to the roaring bitmap in a `std::set`.
This code is stripped out via amalgamation.sh for a release roaring.hh
Having the code in the main class means that any codebase that uses the
C++ object can leverage the tests, so this isn't exercising a distinct
object which was created solely for testing.  It also increases the
likelihood of attention to the checks during code maintenance.
Since std::set stays sorted, the algorithms are not terribly difficult
to have written using iterators.  Though it may not be worth it vs.
using higher level facilities like `set_intersection()` that would
create temporary objects.
The corresponding std::set algorithms are implemented for the inplace
forms of …
=> roaring_checked.hh differential check against std::set

amalgamation.sh, cpp/roaring64map.hh
Users of the C++ class must now use Roaring from namespace `roaring`
The file `amalgamation_demo.cpp` is generated by a shell script, and
the script wasn't modified to use this namespacing.
This also exposed that the 64-bit class was dependent on the api::
namespace inclusion from the unit test.  When that namespace is not
included, it needs to qualify the `roaring_bitmap_t` and iterator
datatypes.
=> Add namespace to generated amalgamation_demo.cpp

cpp/roaring.hh, include/roaring/roaring.h, tests/cpp_unit.cpp
This tweak makes the inclusion of roaring.H under a C++ build pull
the definitions for the C API into global scope.  But an inclusion
of roaring.HH will suppress that `using` statement.
As a result, you can get C compatible semantics when superficially
building a codebase using a C++ compiler.  But purposeful use of
the C++ header will require explicit `using` of the C API.
This strategy resembles the compatibility headers like `stdio.h`
which act like their C counterparts by adding the std:: namespaced
definitions, e.g. of `<cstdio>`, to global scope.
https://stackoverflow.com/q/10460250/cstdio-stdio-h-namespace
=> Global scope API in roaring.h, but not roaring.hh

src/roaring.c
Address sanitizer was reporting memory leaks when running the
`toplevel_unit` tests.  The leaks originated in the inplace
andnot/xor/lazy_xor code, and are connected to the choice to
not perform an inplace operation when a container is shared...
but to call into the non-modifying forms.
The and/or operations have code which checks if the resulting
container from an operation does not match the input and frees
the input container, like:
if (c != c1) {  // in this instance a new container was
// created, and we need to free the old one
container_free(c1, typecode1);
}
There is no such code for andnot/xor/lazy_xor.  Instead the
inplace branches seem to do their own freeing of replaced
containers.  But the non-inplace branch does not account for the
needed drop of a refcount on the shared …
=> Inplace andnot/xor/lazy_xor Shared container leak

amalgamation.sh, cpp/roaring.hh, cpp/roaring64map.hh, include/roaring/roaring.h, include/roaring/roaring_array.h, include/roaring/roaring_types.h, src/roaring.c, src/roaring_array.c, src/roaring_priority_queue.c, tests/realdata_unit.c, tests/toplevel_unit.c
The function roaring_bitmap_contains() in the C API was declared as
inline, pulling in a considerable set of dependencies.  Usage of the
container_contains() function brought in definitions for
bitset_container_t, array_container_t, run_container_t, as well as
all the needed support functions.
While inlining can give considerable advantages, the definition of
this particular public export as inline causes collateral damage
that is unlikely to move the needle much to client performance.
This migrates the implementation of roaring_bitmap_contains() into
roaring.c, and moves the `roaring_array_t` from roaring_array.h
into roaring_types.h.  This then allows containers.h to be removed
from the public API.
Code such as tests that wants to use the internal functions thus
must include the …
=> hide containers.h/roaring_array.h from public api

amalgamation.sh, include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/container_defs.h, include/roaring/containers/containers.h, include/roaring/containers/convert.h, include/roaring/containers/mixed_andnot.h, include/roaring/containers/mixed_intersection.h, include/roaring/containers/mixed_negation.h, include/roaring/containers/mixed_union.h, include/roaring/containers/mixed_xor.h, include/roaring/containers/run.h, include/roaring/roaring.h, include/roaring/roaring_array.h, include/roaring/roaring_types.h, src/containers/containers.c, src/containers/convert.c, src/containers/mixed_andnot.c, src/containers/mixed_intersection.c, src/containers/mixed_negation.c, src/containers/mixed_union.c, src/containers/mixed_xor.c, src/roaring.c, src/roaring_array.c, src/roaring_priority_queue.c
There are currently 4 subclasses of container in roaring.  As it is
a C codebase, their structs do not share a common "base class".  So
when passing around a generic container, void* had to be used.
This commit introduces a new type to capture the intention of a
generic container, called `container_t`.  It is defined as `void` in
the C build, and serves as documentation...which is in itself an
improvement.
However, the C++ build can define container_t as an actual base
class for the containers.  It can do so in a way that doesn't disrupt
the C compatible behavior of the structs, due to the derived class
being standard layout because of the "Empty Base Class Optimization"
https://en.cppreference.com/w/cpp/language/ebo
When this is used, you can assign any subclass xxx_container_t to a …
=> void* -> container_t*, checked in C++ builds

include/roaring/containers/containers.h, src/containers/containers.c, src/containers/convert.c, src/containers/mixed_andnot.c, src/containers/mixed_negation.c, src/containers/mixed_xor.c, src/roaring.c, src/roaring_array.c, src/roaring_priority_queue.c, tests/container_comparison_unit.c, tests/mixed_container_unit.c, tests/toplevel_unit.c
Names like ARRAY_CONTAINER_TYPE_CODE are less belabored if they
are just like ARRAY_CONTAINER_TYPE.  (Longness for the sake of
uniqueness is significantly less of an issue with containers.h
no longer leaking into the public exports.)
This makes that change, as well as using token pasting to shorten
the switch() case instances of CONTAINER_PAIR.  It is split into
two macros, one to use with constants in case labels and one to
use with variables in the switch itself.
Before:
switch (CONTAINER_PAIR(type1, type2)) {
case CONTAINER_PAIR(ARRAY_CONTAINER_TYPE_CODE,
RUN_CONTAINER_TYPE_CODE):
...
}
After:
switch (PAIR_CONTAINER_TYPES(type1, type2)) {
case CONTAINER_PAIR(ARRAY,RUN):
...
}
=> _TYPE_CODE -> _TYPE, CONTAINER_PAIR() shorthand

CMakeLists.txt, tests/array_container_unit.c, tests/bitset_container_unit.c, tests/c_example1.c, tests/container_comparison_unit.c, tests/cpp_random_unit.cpp, tests/cpp_unit.cpp, tests/format_portability_unit.c, tests/mixed_container_unit.c, tests/realdata_unit.c, tests/robust_deserialization_unit.c, tests/run_container_unit.c, tests/test.h, tests/toplevel_unit.c, tests/util_unit.c, tools/cmake/FindCTargets.cmake
The CMake build switch ROARING_BUILD_C_AS_CPP was only being
applied to the main files, and not the tests.  This commit adds
another option for the test files: ROARING_BUILD_C_TESTS_AS_CPP
(Having a separate setting is beneficial, in order to make sure
a C++ built library can be used with C clients...and vice versa)
With this change, there are no `void*` references to containers
or raw casts.  This gives compile time errors when aspects of
the internal interfaces change that would be more difficult to
debug otherwise.
Because there is no compatible way to declare a function across
C and C++ that doesn't name a `void**` argument, this required
making the test functions use a macro: DEFINE_TEST()
=> Make C Tests Compilable in C++ Mode

benchmarks/add_benchmark.c
Seeing error in building the project on macos with below clang version: 
_Apple clang version 12.0.0 (clang-1200.0.32.27)_
_Target: x86_64-apple-darwin19.6.0_
_Thread model: posix_
_InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin_
I think quick fix is to include stdio.h where `printf` is declared. There should be no negative impact to do so.
So send this tiny PR.
=> fix compiling error "implicit-function-declaration" for function printf

benchmarks/bitset_container_benchmark.c, include/roaring/bitset_util.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, src/bitset_util.c, src/containers/bitset.c, src/containers/convert.c, src/containers/mixed_andnot.c, src/containers/mixed_equal.c, src/containers/mixed_intersection.c, src/containers/mixed_negation.c, src/containers/mixed_subset.c, src/containers/mixed_union.c, src/containers/mixed_xor.c, src/roaring.c
Having the bitset container use a unique name for its words array
helps significantly in code understandability, especially when
working with a mixture of array containers and bitset containers.
There is no useful polymorphism from the shared name to be lost.
This also standardizes the parameter name for extracted words
arrays passed to `words` as well (variants were `array`, `bitmap`
and `bitset`).
Some const-correctness and excising of void*/casts included.
=> Rename bitset words array "array" => "words"

benchmarks/real_bitmaps_benchmark.c, include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, include/roaring/containers/convert.h, include/roaring/roaring.h, src/containers/array.c, src/containers/bitset.c, src/containers/convert.c, src/containers/mixed_andnot.c, src/containers/run.c, src/roaring.c
In experimenting with the concept for the exposure of the API roaring_bitmap_t to allocator hooks, the distinction between `roaring_bitmap_t` and `roaring_array_t` becomes important; and routines that have an `ra` need to properly cast it to an `r` to pass through.
*(Note: Given the existence of `array_container_t` it might be better to call it a `roaring_highlow_t` or similar...it's easy to get those two mixed up.)*
This is the outgrowth of trying to normalize taking `r` as the common abbreviation for roaring bitmaps, as exposed in the API.  Since it involved editing several of the comments and prototypes in `roaring.h` I went ahead and tried to tidy up the file as a whole somewhat...until it was diminishing returns to do any more.
There is no (intentional) change in functionality from …
=> r => roaring_bitmap_t, ra => roaring_array_t, cleanups

.github/workflows/ubuntu-ci.yml, CMakeLists.txt, tests/installation/find/CMakeLists.txt
This adds a simple CMake install and test routine. It also moves us to static by default.
Fixes https://github.com/RoaringBitmap/CRoaring/issues/243
=> Let us test installation.

src/roaring_array.c, tests/toplevel_unit.c
Basically, when overwriting a bitmap with an empty source, a contributor has recently added a fast path. The fast path would just free the containers, but it would not adjust the container count, leaving a broken state.
Fixes https://github.com/RoaringBitmap/CRoaring/issues/288
=> Fixes issue 288.

cpp/roaring64map.hh
for_each std::pair<int, Roaring> will generate a extra memory copy
https://github.com/apache/incubator-doris/issues/5855
=> fix memory copy in for_each

README.md
ld gives error on compilation if `#include "roaring.c"` is not added while writing cpp code.
=> including roaring.c

src/roaring_priority_queue.c
Since the size of the heap is not modified during its lifetime we can use a single allocation for the whole thing.
=> Use single allocation for heap

src/containers/mixed_negation.c
The address sanitizer bans arithmetic on `NULL` pointers. Calling `bitset_clear_list` with such an input performs an addition to compare between start and end. Even tho the code is correct (it's used only as the end condition of an iteration), the sanitizer causes a crash.
=> Fix sanitizer crash

src/array_util.c, src/bitset_util.c, src/containers/bitset.c
Hey there :wave: I was reading some code in parallel to the papers and articles and came across a few private functions not marked as such. That's it! Thanks for being amazing and providing not only dope results but also an outstandingly well engineered codebase :raised_hands:
=> Makes helper functions private wrt. translation unit

cpp/roaring64map.hh
use move instead of copy in c++ interface which will get good performance under sparse bitmap
https://github.com/StarRocks/starrocks/pull/86
=> use right value instead of copy value in c++ interface

cpp/roaring64map.hh
Support the case when `buf` is not aligned as uint64_t. For keys such precautions were already taken, for example at line 585:
```
// push map key
std::memcpy(buf, &map_entry.first, sizeof(uint32_t));
// ^-- Note: `*((uint32_t*)buf) = map_entry.first;` is undefined
```
=> Prevent misaligned read/write for map_size

src/roaring.c, tests/add_offset.c
Reported by @Ezibenroc 
Return empty bitmaps on very large and very small offsets. Return CoW bitmaps when the input is CoW.
=> add_offset fixes

src/roaring_array.c
We are not guarding about negative container counts. It is an obvious oversight.
=> This should improve robustness.

src/containers/bitset.c, tests/add_offset.c
Checked the wrong field to free lo_only and hi_only containers.
Addresses #349
=> Fix memory leak in add_offset test

tests/mixed_container_unit.c, tests/robust_deserialization_unit.c, tests/test.h, tests/toplevel_unit.c
Change the `DEFINE_TEST` macro to define static functions: This gives warnings when test functions are never used.
* Call `test_bitset_to_run`, which works as-is
* Remove `test_robust_deserialize8`, which refers to a file which appears to have never been committed
* Call `run_many_negation_range_tests_simpler_*` test functions, after fixing implementation of clamping the topmost-run
* These tests take quite a while to run, should these be changed?
=> Make sure unit tests are actually called

tests/mixed_container_unit.c, tests/robust_deserialization_unit.c, tests/test.h, tests/toplevel_unit.c
Change the `DEFINE_TEST` macro to define static functions: This gives warnings when test functions are never used.
=> Make sure unit tests are actually called (#373)

cpp/roaring.hh, cpp/roaring64map.hh, tests/cpp_random_unit.cpp, tests/cpp_unit.cpp, tests/roaring_checked.hh
These were already present in the C API, but the C++ version only had `Roaring::addRange`. `addRangeClosed` is especially useful in the case of 64-bit integers, where an open range doesn't cover all possible values.
=> Add add/removeRange to Roaring and Roaring64Map

include/roaring/containers/array.h
The rest can be done by checking a single memory location
=> Use a single binary search for array contains_range

cpp/roaring64map.hh, src/containers/convert.c, tests/cpp_random_unit.cpp, tests/cpp_unit.cpp, tests/roaring64map_checked.hh
The implementation of both doublechecked::Roaring64Map and the tests are mostly copied from the 32-bit version. I ran clang-format on the newly added code in tests/cpp_random_unit.cpp. I also added a statement to print the random seed, to reproduce failures only reproduced by specific seeds.
Adding this random test surfaced a few issues:
1. Roaring64Map::isSubset did not work correctly when a Roaring value was empty. It would return false if the key for that value was not found in the other Roaring64Map. The correct behavior is to return true, just as empty Roarings return true for all isSubset calls.
2. Roaring64Map::flip did not check for a valid range.
3. convert_to_bitset_or_array_container would loop forever if run_end == uint16 max.
=> Add doublechecked::Roaring64Map + tests, fix issues found by it

amalgamation.sh, include/roaring/isadetection.h, include/roaring/portability.h
As remarked by @samhames in https://github.com/RoaringBitmap/CRoaring/issues/394, we want isadetection.h to be always included *after* portability.h, never the other way around. Sadly, the amalgamated script would do it in reverse which might cause issues when building under Windows while using the amalgamated script.
=> Fix for issue 394.

tests/toplevel_unit.c
The bulk of this change changes `assert` to `assert_true`. There are a couple other small fixups.
As you know, `assert` is a standard C macro, and `assert_true` is a macro from Cmocka. The main disadvantage of standard C `assert` is that it compiles to a no-op in optimized builds. This is not desirable for these unit tests, which should check their assertions whether running in debug or optimized builds. Cmocka's `assert_true` also provides `__FILE__` and `__LINE__` information.
I think it's likely that the use of `assert` was inadvertent.
=> Unit test cleanups: change assert -> assert_true, a couple other small things

cpp/roaring64map.hh, tests/cpp_unit.cpp
Hello,
The purpose of this PR is to slightly improve the efficiency of `Roaring64Map` in C++.
As you know `Roaring64Map` contains an "outer" `std::map`, which maps the key's high bits to individual (32-bit) Roaring maps, which in turn handle the key's low bits. The problem is that many of the methods in `Roaring64Map` probe the outer map more times than necessary. This includes high-traffic items like `add()` and `contains()`, which probe twice when they only need to probe once.
I've changed a variety of methods to do fewer probes. While I was here I also took the liberty to make a few changes:
* In `flip()`, I added what I believe to be a missing call to `setCopyOnWrite()`
* In `operator &=`,  `operator -=`, and `operator ^=`, if the 32-bit Roaring entry becomes empty, I remove it from …
=> Improve efficiency of outer map operations for Roaring64Map

amalgamation.sh
At the moment, amalgamation generation date is locale-dependent and can't be reliably parsed by external tools.
0.7.2
// Created by amalgamation.sh on Ven  4 nov 2022 11:02:44 EDT
0.6.0
// Created by amalgamation.sh on Wed 20 Jul 2022 16:25:25 EDT
I suggest using ISO 8601 UTC dates instead as an internationally understood universal format
`date -u +"%Y-%m-%dT%H:%M:%SZ"`
// Created by amalgamation.sh on 2022-11-08T08:02:56Z
=> Use ISO 8601 UTC dates as amalgamation timestamps

cpp/roaring64map.hh, tests/cpp_unit.cpp, tests/roaring64map_checked.hh
Improve various "remove"-style operations. The majority of the changes here are adding comments, introducing temporary variables, and adding unit tests. Highlights:
The code in `remove(uint32_t)` and `removeChecked(uint32_t)` had a subtle bug (and was also slightly inefficient). The code for `remove(uint32_t)` was
```
void remove(uint32_t x) { roarings[0].remove(x); }
```
If slot 0 is present, this does the right thing. But if slot 0 is absent, this creates an empty inner bitmap and removes `x` from it, which is a no-op. This is fine so far as it goes, aside from the needless work of making an empty bitmap and leaving it lying around. The problem is that the empty bitmap left behind in slot 0 does not have its copyOnWrite flag set. Normally the code is careful to set this bit …
=> Improve remove-type operations

cpp/roaring64map.hh
`RoaringMap64::select()` had a pointer cast (from `uint64_t*` to `uint32_t*`) that is at best undefined behavior and at worst does the wrong thing on a big-endian machine anyway. Fortunately it's straightforward to rewrite the code so it does not do this pointer casting and does not depend on endianness.
Secondarily the method had an unreachable code path with a `return false`. I felt it was safer to throw an exception if this "unreachable" code was ever executed.
Otherwise the logic of this method is unchanged.
=> RoaringMap64::select(): remove illegal pointer cast; throw exception on unreachable code path.

cpp/roaring.hh, cpp/roaring64map.hh, tests/cpp_unit.cpp
Executive summary:
1. Provided extra entry points for `flip` on both the 32-bit and 64-bit side to make it uniform with `addRange` and `removeRange`
2. Inspired by an idea from @Dr-Emann in https://github.com/RoaringBitmap/CRoaring/pull/397 , used `emplace_hint` to minimize map lookups. The resultant code does only *one* lookup for the whole operation; everything else is just linear iteration through the specified map range, which is cool.
3. Also `flip()` does the same "remove bitmaps if they become empty" logic that the other operations do now.
4. Added unit tests
I like how this one turned out. Kindly let me know what you think.
Some rationale on adding the entry points:
First, provides API uniformity for the end-user, which is always nice.
Second, provides uniformity for the code …
=> Update flip-type operations of Roaring64Map

cpp/roaring64map.hh, tests/cpp_unit.cpp, tests/roaring64map_checked.hh
1. Improve the efficiency of various "add"-style operations by reducing the number of duplicative outer map lookups.
2. Add a private helper method `lookupOrCreateInner` to reduce the number of repetitions of the `setCopyOnWrite` call.
3. Carefully document and rewrite `addRangeClosed` so it is clearer what is going on. Also, for the "middle section", where the method is creating completely full inner Roaring bitmaps, create one "the hard way" and then copy it if you need more. (Note: if there is some more efficient way to create a completely full 32 bit Roaring, please let me know)
4. Change `addMany(size_t, const uint64_t*)` to cache its last outer map lookup and perhaps save a few lookups if there is locality that can be exploited.
=> Improve add-type operations

include/roaring/portability.h
Alternative to https://github.com/RoaringBitmap/CRoaring/pull/407
=> Let us guard the malloc.h include with a check for glibc.

README.md, cpp/roaring.hh, cpp/roaring64map.hh, tests/cpp_random_unit.cpp, tests/cpp_unit.cpp
Basically, we want to be able to do the following:
```C++
Roaring b = Roaring::bitmapOfList({1,2,4});
```
Instead of the awkward
```C++
Roaring  = Roaring::bitmapOf(3, 1, 2, 4);
```
=> add support for initializer list

src/containers/convert.c
Compiling with Clang 15 and lots of warnings reveals this unneeded variable.
=> convert.c: Remove set-but-not-used variable (Clang 15 warning)

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which CRoaring already runs.
CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzer is built on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
=> Add CIFuzz to Github workflows

cpp/roaring.hh, cpp/roaring64map.hh, tests/cpp_unit.cpp
Following up on https://github.com/RoaringBitmap/CRoaring/pull/408 , I thought I'd volunteer this PR now while the topic is still fresh in people's minds and people can discuss the pros and cons here.
My personal TL;DR opinion is that I do think initializer lists vis-à-vis brace constructors introduce some surprises, but those surprises are enough of an edge case to not really matter that much (they can be worked around by not using brace syntax for constructors). So, assuming "informed consent" this seems like a fine change to me.
Also fixed some spacing and comment nits.
=> Add initializer_list constructor and assignment operator to Roaring and Roaring64Map

README.md
For the last year and a half, I've maintained a Zig wrapper here: https://github.com/jwhear/roaring-zig
I don't know if there are any special criteria for inclusion on the README but thought I'd put it out there.
=> Add link to Zig wrapper to README

benchmarks/real_bitmaps_benchmark.c, include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/run.h, include/roaring/portability.h, include/roaring/roaring.h, src/containers/array.c, src/containers/bitset.c, src/containers/run.c, src/roaring.c, tests/toplevel_unit.c
This PR adds the function `roaring_bitmap_t *roaring_bitmap_portable_deserialize_frozen(const char *buf)`, as discussed in #352. This allows deserializing a buffer in the portable format into a frozen bitmap, which is faster than regular deserialization with `roaring_bitmap_portable_deserialize`.
The implementation is a combination of `roaring_bitmap_frozen_view` and `ra_portable_deserialize`. The function makes a single call to `malloc` and uses the "arena allocator" approach from `roaring_bitmap_frozen_view`. Data for the containers point directly into the provided buffer (`buf`). I've included unit tests adapted from testing `roaring_bitmap_portable_deserialize`.
To gauge the performance impact, I've added deserialization to the `real_bitmaps_benchmark` benchmark. The chart below shows …
=> Add roaring_bitmap_portable_deserialize_frozen

src/roaring.c
In roaring-node, roaring.c is compiled as C++ source.
The recent change in the roaring_bitmap_portable_deserialize_frozen that uses arena_alloc causes CPP compilation to fail.
The void* pointer need to be casted to the right pointer type.
=> fix use of arena_alloc for C++ compilers when roaring.c is compiled as C++

include/roaring/array_util.h, src/array_util.c, src/containers/array.c
I notice that in function `array_container_intersection_inplace`, there is no implementation of vectorized inplace intersection, and this slows down the computation.
We can simply use intersect_vector16 to do a non-inplace intersection, and replace the source array with the new one, but this requires frequent memory allocation and freeing. So I think a real inplace intersection is better.
Function `intersect_vector16_inplace` is modified from `intersect_vector16`, which uses `__m128i tmp[2]` for temporary storage of intersection result, to avoid overwritting original numbers in source array that haven't been used.
=> Add intersect_vector16_inplace to enable vectorized inplace intersection between arrays.

src/containers/mixed_union.c
I wonder why `fast_union_uint16` was not used in these 2 functions:
```
array_array_container_inplace_union
array_array_container_lazy_inplace_union
```
I think `union_vector16` is still safe here.
=> Use fast_union_uint16 instead of union_uint16.

src/isadetection.c
I'm getting amalgamation build failures due to a missing semicolon in `isadetection.c`.
=> fix missing semicolon

src/isadetection.c
It seems that when compiling croaring in C++ in a non X64 machine the compilation fails.
The reason seems to be the fact that 
```
#ifdef __cplusplus
} } }  // extern "C" { namespace roaring { namespace internal {
#endif
```
must be after `#endif // defined(__x86_64__) || defined(_M_AMD64) // x64` and not before
Changes:
- fix the order of #endif for when defined(__x86_64__) || defined(_M_AMD64) is false and __cplusplus is true
=> fix the order of #endif for non X64 and compiling in cpp

.gitignore
I use `CRoaring` as an sub_module , but after `cmake` there will leave an annoying empty `dependency/` dir.
don't know why , just ignore it.
=> ignore `dependencies/`

.github/workflows/alpine.yml, .github/workflows/cifuzz.yml, .github/workflows/codeql.yml, .github/workflows/documentation.yml, .github/workflows/macos-ci.yml, .github/workflows/s390x.yml, .github/workflows/ubuntu-ci.yml, .github/workflows/ubuntu-debug-sani-ci.yml, .github/workflows/ubuntu-gcc10-ci.yml, .github/workflows/ubuntu-legacy-ci.yml, .github/workflows/ubuntu-noexcept-ci.yml, .github/workflows/ubuntu-sani-ci.yml, .github/workflows/vs16-arm-ci.yml, .github/workflows/vs16-ci.yml, .github/workflows/vs17-arm-ci.yml, .github/workflows/vs17-ci.yml, .github/workflows/vs17-clang-ci.yml
Closes https://github.com/RoaringBitmap/CRoaring/issues/467
FYI I have verified that all SHAs belong to the original repositories, not forks, which is a caution we must have.
------
Refs:
https://github.com/actions/checkout/releases/tag/v2.7.0
https://github.com/actions/checkout/commit/ee0669bd1cc54295c223e0bb666b733df41de1c5
https://github.com/actions/checkout/releases/tag/v3.5.2
https://github.com/actions/checkout/commit/8e5e7e5ab8b370d6c329ec480221332ada57f0ab
https://github.com/google/oss-fuzz/commit/d318097b285bc695f785b98d40c2d058c0f438b5
https://github.com/actions/upload-artifact/releases/tag/v3.1.2
https://github.com/actions/upload-artifact/commit/0b7f8abb1508181956e8e162db84b466c27e18ce
https://github.com/github/codeql-action/releases/tag/v2.3.2 …
=> Reference actions by commit SHA

src/isadetection.c
Operating systems such as OpenBSB might allow us to build software with AVX-512 enabled, but may not actually run AVX-512 code.
=> Checking OS support for AVX-512

include/roaring/containers/containers.h, include/roaring/portability.h, src/containers/containers.c, src/isadetection.c, src/roaring.c
It feels quite a bit cleaner to me to have the implementations of how to deal with atomic integers centralized like this.
=> Use typedef/inline functions to centralize atomic ref count ops

include/roaring/containers/bitset.h, include/roaring/isadetection.h, include/roaring/portability.h, include/roaring/roaring_array.h, src/bitset.c, src/containers/array.c, src/isadetection.c
This pull request fixes a small handful of compilation issues noticed when integrating CRoaring into the Git project and compiling it with `DEVELOPER=1` enabled.
When compiling without Git's strict checks, everything works as expected (here and elsewhere I'm using the amalgamation build):
```ShellSession
$ make croaring/roaring.o
* new build flags
CC croaring/roaring.o
```
However, Git cannot compile the amalgamated build when `DEVELOPER=1` is set. Setting `DEVELOPER=1` when building enables a [handful of stricter compilation checks](https://github.com/git/git/blob/9e49351c3060e1fa6e0d2de64505b7becf157f28/config.mak.dev), including `-Werror=implicit-function-declaration`, `-Werror=old-style-definition`, `-Werror=missing-prototypes`. Compiling CRoaring with those flags does not currently …
=> Fix a handful of compilation issues with older C standards

include/roaring/portability.h
When building CRoaring without support for atomics (for instance, in a pre-C11 environment where <stdatomic.h> is not part of the language specification), we get a compile-time message that copy-on-write bitmaps are unavailable.
Having a warning message is useful as a default behavior, since it can prevent surprises for CRoaring users who expect their bitmaps to be thread-safe, but aren't for whatever reason.
But in environments where we know that <stdatomic.h> is unavailable, or we are single-threaded, the message is noise, since we know ahead of time that CRoaring's bitmaps won't be threadsafe (and are OK with that).
Provide an opt-out build knob (CROARING_SILENT_BUILD) to suppress this warning for applications that wish to do so.
##
=> portability.h: add an build flag to suppress warnings

amalgamation.sh
Since users may check in the output of the amalgamation, ensure that the source files are generated in a common order from run to run.
Use a more straightforward invocation of git ls-files.
Fail early if the source path contains whitespace, which will break the amalgamation script.
=> amalgamation.sh: Sort the C files in the output

include/roaring/roaring.h, src/roaring.c, tests/toplevel_unit.c
CRoaring offers `roaring_bitmap_portable_deserialize_safe` but it does not provide `roaring_bitmap_deserialize_safe`.
- Add new function `roaring_bitmap_t *roaring_bitmap_deserialize_safe(const void *buf, size_t maxbytes);`
- Add some basic unit tests for it
=> Add roaring_bitmap_deserialize_safe

include/roaring/bitset/bitset.h, include/roaring/roaring.h, src/bitset.c, src/roaring.c
Don't use `static inline` for functions meant to be part of the API, so they should always get an external linkage version. `static inline` and `extern inline` shouldn't even work together, but it seems they do.
See #489, #487, #488
=> Use `inline` in headers, `extern inline` in c files

cpp/roaring.hh, include/roaring/roaring.h, tests/cpp_unit.cpp
This patch adds:
1. `BulkContextWrapper` as a wrapper for `api::roaring_bulk_context_t`
2. `addBulk`, as a wrapper for `api::roaring_bitmap_add_bulk`
I'm not so familiar with C++ wrapper, but I'm glad to learn and resolve the problems in my code
=> C++ Wrapper for Roaring32 `*Bulk`

cpp/roaring64map.hh
Use a single search of the map, rather than `find` and sometimes `lower_bound`, use a single `lower_bound` call.
=> Simplify roaring64map rank

include/roaring/portability.h, tests/mixed_container_unit.c
Fixes https://github.com/RoaringBitmap/CRoaring/issues/495
=> Removing a static qualifier

include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, include/roaring/containers/run.h, include/roaring/portability.h, include/roaring/roaring.h, src/containers/array.c, src/containers/bitset.c, src/containers/containers.c, src/containers/run.c, src/roaring.c, tests/test.h, tests/toplevel_unit.c
Adds the function `roaring_bitmap_internal_validate` which validates assumptions that other code relies on (e.g. arrays are sorted and non-duplicated).
This may be useful for e.g. validating the result of deserializing, but mostly, it allows for an easy check to sprinkle through the unit tests to ensure the bitmap is always in a consistent state.
=> Add a function to do internal validations of the bitmap, intended for testing

include/roaring/portability.h
This allows the core library to build on illumos (the C++ benchmarks don't build due to a different issue surrounding the use of the `restrict` keyword that I can file).
=> Define __EXTENSIONS__ on illumos

src/roaring_array.c, tests/toplevel_unit.c
The previous code would happily accept and create _huge_ allocations (up to 22 GiB) for up to 2 billion containers. However, we know the maximum number of containers possible, so we instead clamp to that value.
This leads to two changes:
- When requesting more than 2^16 containers, we will only allocate space for 2^16 containers
- When requesting more than 2^31 containers, we will no longer error
=> Keep capacity sane when creating a bitmap with a capacity

include/roaring/roaring.h
Document the return value, and what the state will be on error
Fixes #342
=> Add more docs to `roaring_bitmap_overwrite`

.github/workflows/macos-ci.yml, CMakeLists.txt
Fixes https://github.com/RoaringBitmap/CRoaring/issues/501
=> Fixing issue 501

src/containers/mixed_union.c
PR https://github.com/RoaringBitmap/CRoaring/pull/452 by @CharlesChen888 introduced an optimization that could be 'argued' to be safe. @feng-y reported problems and they blamed this PR.
I am not able to fault PR https://github.com/RoaringBitmap/CRoaring/pull/452  when using mainstream compilers, but with the Intel compiler, we fail the tests (see my observation https://github.com/RoaringBitmap/CRoaring/issues/506).
So I am reverting it.
It might be possible to make this safe under all compilers, but it will require more care.
=> Reverting PR 452

README.md, fuzz/croaring_fuzzer.c, src/containers/array.c, src/containers/run.c, src/roaring.c, src/roaring_array.c, tests/c_example1.c, tests/toplevel_unit.c
This also removes several 'fprintf' that are unwarranted in a library.
Refers to https://github.com/RoaringBitmap/croaring-rs/pull/119
=> Improves the documentation of roaring_bitmap_internal_validate

include/roaring/portability.h, src/containers/run.c, tests/toplevel_unit.c
We can miss an issue whereas the run containers overflow the 16-bit boundary.
=> Caught a bug in roaring_bitmap_internal_validate

src/isadetection.c
This *should* (*) fix [a race](https://github.com/ClickHouse/ClickHouse/issues/55270) detected by tsan in ClickHouse which uses croaring in various places. Feel free to modify/improve the PR.
(*) I could not reproduce the original issue locally, therefore I only *quite sure* that this really solves the problem.
=> Hardware detection: Try to access 'support' only atomically

cpp/roaring.hh, include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, include/roaring/containers/run.h, include/roaring/roaring.h, microbenchmarks/bench.cpp, src/containers/bitset.c, src/containers/run.c, src/roaring.c, tests/cpp_unit.cpp, tests/toplevel_unit.c
this pr provide an api implementation for fast getting `rank` of many elements in bulk mode.
as well as test/benchmark.
```
$ microbenchmarks/bench --benchmark_filter="RankMany*"
2023-11-29T09:55:50+08:00
Running microbenchmarks/bench
Run on (36 X 4600 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x18)
L1 Instruction 32 KiB (x18)
L2 Unified 1024 KiB (x18)
L3 Unified 25344 KiB (x1)
Load Average: 0.57, 0.73, 0.61
AVX-2 hardware: yes
AVX-512: supported by compiler
AVX-512 hardware: no
In RAM volume in MiB (estimated): 1.802828
benchmarking other files: You may pass is a data directory as a parameter.
data source: CRoaring/benchmarks/realdata/census1881
number of bitmaps: 200
x64: detected
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra …
```
=> add roaring_bitmap_rank_many(): get `rank()` values in Bulk

.github/workflows/alpine.yml, .github/workflows/macos-ci.yml, .github/workflows/s390x.yml, .github/workflows/ubuntu-ci.yml, .github/workflows/ubuntu-debug-sani-ci.yml, .github/workflows/ubuntu-gcc10-ci.yml, .github/workflows/ubuntu-legacy-ci.yml, .github/workflows/ubuntu-noexcept-ci.yml, .github/workflows/ubuntu-sani-ci.yml, .github/workflows/ubuntu-sani-thread-ci.yml, .github/workflows/vs16-ci.yml, .github/workflows/vs17-ci.yml, .github/workflows/vs17-clang-ci.yml, CMakeLists.txt, README.md, include/roaring/portability.h, src/roaring.c
Fixes https://github.com/RoaringBitmap/CRoaring/issues/530
=> fixing issue with accidentally disabled tests.

CMakeLists.txt, microbenchmarks/CMakeLists.txt, tools/cmake/FindCTargets.cmake
Add `ROARING_USE_CPM` option (ON by default), so that it can use CPM to deal with dependencies or use system dependencies, which it is helpful for packager to use the option of enabling tests.
=> Add ROARING_USE_CPM option in CMake

tests/toplevel_unit.c
The latest test we added has a memory leak. This should fix it.
=> fixing memory leak

cpp/roaring.hh, cpp/roaring64map.hh, include/roaring/containers/array.h, include/roaring/containers/run.h, src/containers/array.c, src/containers/bitset.c, src/containers/run.c, tests/cpp_unit.cpp
As tittle. `roaring_bitmap_portable_deserialize_frozen` was not supported in the C++ API, this PR adds it for both `Roaring` and `Roaring64Map`, and adds tests.
=> Add support for portable_deserialize_frozen to C++ API

src/art/art.c, tests/art_unit.cpp
Using > caused it to skip the first child. Only applies to `node48` and `node256` Modified an existing test to cover this case.
=> Use >= instead of > for art_node*_prev_child

include/roaring/containers/containers.h, include/roaring/roaring.h, include/roaring/roaring_types.h, src/containers/containers.c, src/roaring.c, tests/toplevel_unit.c
This PR moves logic for iterating within containers into `containers.h`, and adds a new `roaring_container_iterator_t` struct for that purpose. `roaring_container_iterator_t` is defined in `roaring_types.h` because it's exposed through `roaring_uint32_iterator_t`. In theory it seems possible to hide `roaring_uint32_iterator_t`, but since exposed already that would have to be done with consideration.
Functionally this should be a no-op. I did make some cosmetic changes and ran clang format on the modified code.
Although it would make the code simpler, I did not include a pointer to the current container and the current typecode in the iterator to avoid duplicating more state. I'm flexible on this though!
=> Move in-container iteration into containers.h

src/roaring64.c, tests/roaring64_unit.cpp
`container_add_range` is from `[min, max]`, no need to add one: https://github.com/RoaringBitmap/CRoaring/blob/f3ad2f2e52c53d0241a6327bdf193423c47059c0/include/roaring/containers/containers.h#L2377
Add a test to verify adding a range to an existing container works correctly
=> roaring64: container_add_range _is_ inclusive

src/roaring64.c, tests/roaring64_unit.cpp
When the bulk context was null, it assumed there was no leaf at all, but that's not nessisarily true.
=> fix(roaring64): add_bulk of existing values no longer reads OOB

src/roaring64.c, tests/roaring64_unit.cpp
This would lead to all sorts of issues: `typecode2` is read uninitialized, and hopefully just asserts that it's not one of the known typecodes. Then, we've stored a null container into the bitmap.
=> roaring64: container_remove_range returns null rather than returning an empty container

src/art/art.c, tests/roaring64_unit.cpp
If a leaf shared all but the last byte, art_find_at could return the incorrrect leaf, rather than returning NULL
Fixes #552
=> fix(roaring64): art_find_at would return the wrong leaf

tests/roaring64_unit.cpp
This should provide better error messages. Apparently `assert_int_equal` also allows comparisons of wider types like `uint64`.
=> Use assert_int_equal instead of assert_true for integer comparisons

include/roaring/containers/containers.h, src/roaring64.c, tests/roaring64_unit.cpp
Fixes #555 
`container_iandnot` frees the original container if necessary. Interestingly, as far as I can tell `container_iand` does not. Added a test for both.
=> Fix double free in roaring64 andnot_inplace

include/roaring/roaring.h, src/containers/array.c, src/containers/bitset.c, src/containers/run.c, tests/toplevel_unit.c
When validating a container, we should reject it if it is empty.
The Roaring format does not allow empty containers.
=> We do not allow empty containers as part of the specification.

include/roaring/containers/containers.h, include/roaring/roaring64.h, microbenchmarks/bench.cpp, src/containers/containers.c, src/roaring64.c, tests/roaring64_unit.cpp
For issue #549: "The ability to do external iteration (an iterator type that the caller controls arbitrarily)".
I decided not to expose the iterator type, because it would need to pull in a lot of stuff from ART. I'm open to changing this though.
=> Add a roaring64 iterator and functions for it

src/art/art.c, tests/art_unit.cpp, tests/roaring64_unit.cpp
Fixes #559 
1. Leaf keys were written to the wrong location: `memcpy(&leaf->key` instead of `memcpy(leaf->key`
2. In `art_node_iterator_lower_bound`, we did not check if the key chunk for the lower bound child was greater than the key chunk we searched for.
3. In `art_iterator_erase` there were a few issues that would lead to an incorrect location. I've somewhat sidestepped the most tricky bit by doing a lower bound search from the root instead.
Added tests for 1 and 2. Also slightly improved `art_printf` for debugging.
=> ART: Fix a few issues around lower bound / erase

include/roaring/portability.h, src/art/art.c, tests/art_unit.cpp, tests/roaring64_unit.cpp
When removing from a node48, the child is simply set to NULL. For example, if the state is (ignoring that it actually needs at least 17 items to not be a node16):
```
keys: {[0]=0, [1]=1}
children: {[0]=child1, [1]=child2}
count: 2
```
After removing key 0, the state will be:
```
keys: {[0]=48, [1]=1}
children: {[0]=NULL, [1]=child2}
count: 1
```
If we then try to insert at key 3, the item at `children[count]` is already in use: we have to find and reuse the 0th child.
Rather than matching the [java implementation][1] (though see the first commit [7dbad58](https://github.com/RoaringBitmap/CRoaring/pull/565/commits/7dbad58b2e92654465f00c9fc92baa902f57e823)), keep a bitset of available children slots. This slightly increases the size of the node48 struct, but it means:
* We don't have to …
=> node48 children can have holes

include/roaring/roaring.h, include/roaring/roaring64.h, src/roaring64.c, tests/roaring64_unit.cpp
Also fixed a bug in `roaring64_iterator_move_equalorlarger` where we didn't compare the correct high bits (modified an existing test to catch this).
=> roaring64: implement intersect_with_range

README.md, include/roaring/roaring.h, include/roaring/roaring64.h, tests/c_example1.c, tests/cpp_unit.cpp, tests/roaring64_unit.cpp, tests/threads_unit.cpp, tests/toplevel_unit.c
Using a macro allows us to count the number of items passed, and avoid having to explicitly pass the count as the first parameter.
=> Replace `roaring{,64}_bitmap_of` with `roaring{,64}_bitmap_from` macro

src/roaring64.c, tests/roaring64_unit.cpp
Fixes #571. This adds a check for when the iterator position is after the start of the range.
Also added a test.
=> Fix roaring64_bitmap_contains_range when the range starts before the first present container

include/roaring/containers/containers.h, include/roaring/roaring64.h, microbenchmarks/bench.cpp, microbenchmarks/bench.h, src/containers/containers.c, src/roaring64.c, tests/roaring64_unit.cpp
=> Implement roaring64_bitmap_to_uint64_array

src/roaring64.c, tests/roaring64_unit.cpp
=> Fix r64 contains range when max is divisible by 2^16

src/roaring64.c, tests/roaring64_unit.cpp
Fixes #574.
Previously calling `roaring64_iterator_previous` after `roaring64_iterator_advance` returned false would not move the iterator. With this commit, this behavior and its inverse are both possible.
I chose to implement this by adding a new field in the iterator to indicate saturation. Another option would be to allow the ART iterator to allow moving from beyond the start / end, but that would require changing the index to a signed integer and thus take up more space.
=> r64 iterator: allow moving from beyond the start / end

.git-blame-ignore-revs
Since the PR was squashed into one commit, the commit hash in .git-blame-ignore-revs was incorrect.
=> Correct commit hash of format commit for blame

include/roaring/art/art.h, src/art/art.c, src/roaring64.c, tests/art_unit.cpp, tests/roaring64_unit.cpp
Fixes #575. This adds the ability to move backward to both the ART iterator and the roaring64 iterator.
=> r64 iterator: allow moving backward with move_equalorlarger

src/roaring64.c, tests/roaring64_unit.cpp
Avoid integer overflow with prev_high48_bits
Also, add tests for all the range based tests with the max container
=> fix: roaring64_bitmap_contains_range now works with ranges starting at the max container

include/roaring/art/art.h, include/roaring/roaring64.h, src/art/art.c, src/roaring64.c, src/roaring_array.c, tests/art_unit.cpp, tests/roaring64_serialization.cpp, tests/roaring64_unit.cpp
Add calls to validate the bitmap around the unit tests
=> Implement roaring64_bitmap_internal_validate

cpp/roaring64map.hh
This patch contains two simple optimizations:
1. For `Roaring64Map::addMany(uint64_t)`, trying to use `BulkContext` to cache the last context
2. For `Roaring64Map::contains`, change `count` + `at` to `find`
=> Optimize C++ roaring64 contains and addMany

cpp/roaring64map.hh, tests/cpp_unit.cpp
See https://github.com/RoaringBitmap/CRoaring/issues/589.
Fixed by turning the map reference into a pointer, in which case the default copy assignment operator will do the right thing. (`std::reference_wrapper` would also have worked, but I find that way too pedantic.)
Now that we did this, we don't need `map_begin` and `map_end` any more -- just call `p->cbegin()` and `p->cend()` as needed. (map iterators are very cheap to construct)
Now that we did this, we don't need the difference between `Roaring64MapSetBitForwardIterator` and `Roaring64MapSetBitBiDirectionalIterator` -- I made`Roaring64MapSetBitBiDirectionalIterator` the only iterator and added typedefs as needed for backwards compatibility. 
Added a test, all tests pass.
=> Change map when copying Roaring64MapSetBitForwardIterator

src/roaring64.c, tests/roaring64_unit.cpp
Only visit existing nodes, rather than every possible container in the range
This makes it feasible to use `roaring64_bitmap_remove_range_closed(r, 0, UINT64_MAX)`. Before, this would have taken forever, but now, it takes proportional time to the number of containers to remove.
See #549 (the first checkbox)
=> Simplify, and optimize roaring64_bitmap_remove_range_closed

include/roaring/art/art.h, tests/art_unit.cpp, tests/roaring64_unit.cpp
Fixes #593. With a max-depth ART, it's possible to have the following node structure, where `N4 = Node4`, `L = Leaf`:
```
N4 --> N4 --> N4 --> N4 --> N4 --> N4 --> L
\-> L  \-> L  \-> L  \-> L  \-> L  \-> L
```
ART iterators carry around a frame per node in the path to the leaf, including the leaf. This can therefore result in 7 frames: one for each differing key byte, plus the leaf node itself.
To handle this case we therefore need 7 iterator frames rather than 6.
=> r64: Increase number of frames in ART iterator

src/art/art.c, src/roaring64.c, tests/art_unit.cpp, tests/roaring64_unit.cpp
Fixes #594. Previously `roaring64_iterator_move_equalorlarger` would only return a valid result if the iterator was positioned within the bitmap. With this, the iterator is allowed to start outside the bitmap.
=> r64: allow _move_equalorlarger to move from beyond the ends of the bitmap

src/containers/containers.c
Compiling CRoaring on Windows (tried on Windows 2019 in CI for roaring-node) causes a compilation error due to the use of (cast){initializer} used in C roaring source code.
(roaring_container_iterator_t){ ... } does not compile in Visual Studio when compiling in C++,
it fails with C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
For reference, https://github.com/SalvatorePreviti/roaring-node/actions/runs/8102601181/job/22145475666
I think the solution is to replace (roaring_container_iterator_t){ ... } with roaring_container_iterator_t{ ... } depending if compiling for C or C++.
This PR defines a macro in containers.c that is (roaring_container_iterator_t) when compiling in C and roaring_container_iterator_t when compiling in …
=> fix C4576 compilation error when compiling CRoaring in C++ on Windows

CMakeLists.txt, src/isadetection.c
In Visual Studio's last few C++ compilers (starting with VS 17.8), you can write code that relies solely on AVX2,  and it may compile to AVX-512 instructions. See screenshot.
Related problems were reported to Microsoft by several folks and reportedly fixed in 17.9, but according to our tests, it is not fixed.
This is a critical issue that can lead to crashing software. Unfortunately, you may not see it until you test it on hardware that does not support AVX-512.
Thus, we are disabling AVX optimizations on recent Visual Studio C++ compilers.
Related threads/findings:
[Original find](https://github.com/RoaringBitmap/croaring-rs/pull/128#issuecomment-1918419461)
[Microsoft bug report](https://developercommunity.visualstudio.com/t/Invalid-AVX512-instructions-generated-wh/10521872)
=> disabling AVX routines under Visual Studio

include/roaring/array_util.h, include/roaring/bitset/bitset.h, include/roaring/bitset_util.h, include/roaring/containers/run.h, include/roaring/misc/configreport.h, include/roaring/portability.h, src/art/art.c, src/bitset.c, src/containers/bitset.c, src/containers/mixed_andnot.c, src/containers/mixed_negation.c, src/containers/run.c, tests/mixed_container_unit.c, tests/threads_unit.cpp
This issues with our macros: mostly lack of prefixing, but also a build issue reported by @dg0yt due to a missing byteswapping function.
=> various fixes to macros

benchmarks/add_benchmark.c, benchmarks/containsmulti_benchmark.c, src/art/art.c, src/roaring.c, src/roaring64.c, tests/toplevel_unit.c
Mostly nitpicking but one change is significant...
This expression looks wrong...
```
context->high_bytes != high48
```
I am not sure what an array-to-array comparison does in C.
=> fix: correct struct init + one array to array comp.

include/roaring/roaring_types.h, src/roaring.c
implement https://github.com/RoaringBitmap/CRoaring/issues/619
=> optimize roaring_bitmap_statistics (breaking change)

include/roaring/roaring64.h, src/roaring64.c, tests/roaring64_unit.cpp
See #549
Add `roaring64_bitmap_range_closed_cardinality` and `roaring64_bitmap_clear` functions
=> Add some missing roaring64 functions

src/roaring64.c
Before submitting this PR, run `tools/clang-format.sh` on your changes. See the "Contributing" section in the README for details.
=> roaring64: Don't crash on roaring64_bitmap_free(NULL)

include/roaring/portability.h, src/art/art.c, src/roaring.c, src/roaring64.c
Alternative to https://github.com/RoaringBitmap/CRoaring/pull/631 using macros instead of new functions.
This PR @madscientist's proposal.
=> fix: introduce macro to initialize to zero structs portably

src/art/art.c, tests/art_unit.cpp, tests/roaring64_unit.cpp
Fixes #635, and adds some tests
@SLieve, is this the right place to do this? The segfault under valgrind:
```
[ RUN      ] test_intersect_with_range
==648093== Invalid read of size 1
==648093==    at 0x12A894: art_node_iterator_lower_bound (art.c:1633)
==648093==    by 0x12AB9F: art_iterator_lower_bound (art.c:1696)
==648093==    by 0x120D2B: roaring64_iterator_move_equalorlarger (roaring64.c:2087)
==648093==    by 0x11E5DB: roaring64_bitmap_intersect_with_range (roaring64.c:1126)
==648093==    by 0x10F3F7: (anonymous namespace)::test_intersect_with_range(void**) (roaring64_unit.cpp:1058)
==648093==    by 0x15B74B: cmocka_run_one_test_or_fixture (cmocka.c:2801)
==648093==    by 0x15BA3F: cmocka_run_one_tests (cmocka.c:2909)
==648093==    by 0x15BF67: _cmocka_run_group_tests …
```
=> Fix segfault with roaring64 intersect_with_range and empty bitmap

.gitignore
Currently, the gitignore tries to ignore src/roaring.c
This actually only works in git because git only considers the gitignore when it would _add_ a file to be tracked, changes to existing files already in git are tracked regardless of what's in .gitignore.
Fixes #637
=> Only ignore amalgamation files at the root

benchmarks/run_container_benchmark.c, src/containers/run.c
https://github.com/RoaringBitmap/CRoaring/issues/454
1. support AVX for run_container_to_uint32_array
2. add dense range for run container
benchmark result:
sparse:
|values| baseline | AVX2 |
|---| ------ | ------ |
|256| 3.64 cycles | 3.68 cycles |
|2018| 3.07 cycles | 3.07 cycles |
|14498| 3.47 cycles | 3.57 cycles |
dense:
|values| baseline | AVX2 |
|---| ------ | ------ |
|7826| 0.18 cycles | 0.10 cycles |
|8152| 0.18 cycles | 0.10 cycles |
|8189| 0.18 cycles | 0.10 cycles |
|8191| 0.18 cycles | 0.10 cycles |
=> support AVX2 for run_container_to_uint32_array

README.md, src/containers/array.c, src/containers/bitset.c, src/containers/run.c
See commit https://github.com/RoaringBitmap/CRoaring/commit/eb5395b649fc15ae8fb6058c2b46cbec6a16cb51 where I added these checks.
Might fix https://github.com/RoaringBitmap/CRoaring/issues/345
=> fix: remove null checks before free. Reverses commit eb5395b

include/roaring/roaring64.h, src/roaring64.c, tests/roaring64_unit.cpp
This allows creating a 64 bitmap cheaply from a roaring_bitmap_t. Ideally, we should add a `roaring64_bitmap_add_offset` too.
Related to #549 
Open to naming suggestions
=> Add `roaring64_bitmap_move_from_roaring32` function

include/roaring/portability.h
=> adding deprecation to MSC_VER

include/roaring/memory.h
When using [clang modules][1] (not C++ modules) #including stuff within `extern "C"` blocks causes warnings. Remove said warnings by moving the #include. See this [StackOverflow question][2] for an idea of what the warning looks like.
[1]: https://clang.llvm.org/docs/Modules.html
[2]: https://stackoverflow.com/questions/77113501/xcode-15-compile-error-import-of-c-module-zlib-appears-within-extern-c-la
Before submitting this PR, run `tools/clang-format.sh` on your changes. See the "Contributing" section in the README for details.
=> Remove `-Wmodule-import-in-extern-c` warnings

CMakeLists.txt, include/roaring/roaring64.h, src/CMakeLists.txt
We shouldn't be expecting `roaring.h` to be available in the header search path directly.
=> import roaring.h from the right place

src/bitset_util.c
The "BLSI" logic is essentially a complicated way to get to BLSR, so refactor to be more explicit.
=> clarify bitset_extract_setbits scalar code (BLSI -> BLSR)

src/roaring64.c, tests/roaring64_serialization.cpp
The added test fails in ASAN without this change with an out-of-bounds read when `art_insert_at` computes a common prefix of 6 (all 48 bits), and tries to read the first non-matching byte of the key at https://github.com/RoaringBitmap/CRoaring/blob/9526ecf2edafdf5b61635763e84e7ef30eaff62b/src/art/art.c#L1172-L1175
=> fix: possible segfault in 64 bit deserialize_safe

src/roaring64.c, tests/roaring64_serialization.cpp
Actually update the previous_high32 variable to ensure the high keys are actually strictly increasing
=> fix: another segfault in 64 bit deserialize_safe

benchmarks/containsmulti_benchmark.c, cpp/roaring.hh, cpp/roaring64map.hh, include/roaring/roaring.h, src/roaring.c, tests/cpp_example2.cpp, tests/cpp_unit.cpp, tests/roaring_checked.hh
These changes aim to improve the consistency of the C++ API between the 32-bit version and the 64-bit version.
Related issues: #629 
Changes:
- Rename `RoaringSetBitForwardIterator` to `RoaringSetBitBiDirectionalIterator` (the old one is now deprecated).
- Add methods: `Roaring::clear` `Roaring::isFull` `Roaring::containsRangeClosed`.
- Revise `move_equalorlarger` methods in iterators.
- Add the `api::roaring_bitmap_flip_inplace_closed` method.
- Add the `api::roaring_bitmap_contains_range_closed` method.
- Add the `api::roaring_bitmap_flip_closed` method.
- Add the `api::roaring_bitmap_range_cardinality_closed` method.
- Other minor changes.
If merged, only the following methods remain that are only implemented in the 32-bit version(in class `Roaring`) but not in the 64-bit version(in …
=> Improve consistency in the C++ interface

fuzz/croaring_fuzzer.c
We do not, currently, ensure that `roaring64_bitmap_portable_deserialize_safe` leaves the bitmap in a proper state after deserialization. This addition to the fuzzer might help.
Related to https://github.com/RoaringBitmap/CRoaring/issues/662
=> adding roaring64 to fuzzer as a step toward solving issue 662

README.md, fuzz/croaring_fuzzer.c, include/roaring/roaring.h, include/roaring/roaring64.h
We now guarantee that deserialization from untrusted sources is safe.
Note that users should still use checksums to validate content integrity. We will not be providing checksumming as there are excellent librairies for this purpose already.
=> safety guarantees about deserialize_safe & internal_validate functions

include/roaring/roaring.h
For more convenience.
(The additional build time is trivial, these headers compile very fast.)
=> including roaring64.h in roaring.h

include/roaring/bitset/bitset.h, tests/cbitset_unit.c
`bitset_next_set_bits` was returning incorrect values for bits set within the same word as the start position when the start position is not a multiple of 64. The values within the word would be reported as lower than they should be by `*start % 64`: e.g. a with `*start = 65`, and a bit at 69, the first result would be `68` (`69 - (65 % 64)`). This was especially confusing for start positions between 0-64: it would appear that `bitset_next_set_bits` was returning _relative_ positions, then suddenly it would jump to absolute positions starting at values >= 64.
Instead, `bitset_next_set_bits` will now correctly always return absolute bit positions.
Fixes #691
=> fix bitset_next_set_bits when called with non-word-aligned starts

include/roaring/portability.h
It would be better if we did not need this macro.
=> defining the macro _GNU_SOURCE appears to create troubles in some cases.

include/roaring/art/art.h, include/roaring/roaring64.h, microbenchmarks/CMakeLists.txt, microbenchmarks/synthetic_bench.cpp, src/art/art.c, src/roaring64.c, tests/art_unit.cpp, tests/roaring64_unit.cpp
This PR makes the following changes:
* Change the internals of both ART and roaring64 to be based on indices into arrays rather than pointers.
* Use `uint64_t` as the value of the ART rather than a pointer, which allows the ART to self-contain its serialization code.
* Add support for frozen (de)serialization. This is done by serializing the arrays of objects and indices into them, which means that during deserialization the calls to `memcpy` are limited and the bitmap can mostly act as a view into a buffer.
* Add some benchmarks using synthetic data for roaring64 / roaring 64 C++ / `std::set`. These benchmarks focus more on the higher-order bits than the current microbenchmarks, and thus are a better test case for 64-bit bitmaps.
This is a large change so there is lots of room for …
=> Add frozen support to roaring64

src/roaring64.c, tests/roaring64_unit.cpp
Before, this would lead to errors where adding and removing a container would leave a container in the list.
=> fix: remove container from roaring64 when removing last item in container

src/roaring.c
container_nonzero_cardinality has to do less work for bitset/run containers than calculating the full cardinality.
=> perf: speed up roaring_bitmap_remove

src/roaring64.c, tests/roaring64_unit.cpp
If the alignment isn't respected, we'll end up padding to the wrong offsets, so just reject it outright.
=> fix: check required alignment in roaring64_bitmap_frozen_view

tests/toplevel_unit.c
There are only 28 bytes of data, but a size of 36 was being passed. Instead, make this impossible: convert to a stack array, and use sizeof rather than a magic number to pass the length of data.
It isn't clear where the test data came from: the linked issue includes a base64 input of `OjAAAAEAAAAAAAkAEAAAADIAMwA0ADUANgA3ADgAOgA7ADwA`, which _does_ expand to 36 bytes, so additionally, this replaces the test data with the decoded value of the data from the linked issue instead.
This was (correctly) failing in ASAN when we immediately read past the end of the string literal.
This is a bug, but a bug that only exists in the tests, no actual CRoaring code is affected.
=> fix: avoid out of bounds index in PyRoaringBitMap124 test

microbenchmarks/synthetic_bench.cpp
I tried compiling with microbenchmarking enabled : 
```
cmake -B build -D ENABLE_ROARING_MICROBENCHMARKS=ON
cmake --build build
```
However, I got a compile error (Arch Linux, g++ 15.2.1) because of a missing standard header.
This PR just adds the missing header.
=> fix build error when microbenchmarking is enabled

src/roaring_array.c
Fixed an issue: missed replacing "free" with "roaring_free" in ra_range_uint32_array()
=> Fixed an issue: missed replacing "free" with "roaring_free"

src/roaring_array.c
Actually, in ra_portable_serialize.
There's no need to allocate an array for the run container bitset, then copying into the destination buffer. Instead, write directly into the destination buffer.
=> remove an unneded allocation in roaring_bitmap_portable_serialize

cmake/config.cmake.in, src/CMakeLists.txt
The current approach of writing the exported targets directly to the config file produces a functional set of targets in the base case of a simple `find_package` call, but any version constraint provided to `find_package(roaring <version>)` will cause any installation to be considered invalid because no version file is published. To support that use case, this PR writes a version file as part of the CMake configure. To make the version values accessible in downstream packages (i.e. in a CMakeLists.txt file that contains `find_package(roaring...)`) this PR also adds a basic config.cmake.in file that is configured using standard CMake helpers and includes both the targets file and the version file. To simplify testing of this particular change as well as any future changes to CRoaring, the …
=> Support version constraints when finding CRoaring with CMake

src/roaring64.c, tests/roaring64_unit.cpp
When we remove a container we need to reset the leaf in the context, as it is no longer valid. Added unit tests to validate. Fixes #742.
=> Fix roaring64_bitmap_remove_many when removing a container
