.clang-format, benchmarks/benchmark.h, benchmarks/bitset_container_benchmark.c, include/containers/bitset.h, src/containers/bitset.c, tests/bitset_container_unit.c, tests/unit.c
* code reformat
* usage of bool type
* usage of const keyword
* usage of __attribute(align) and fixed array for bitset_t
=> Multiples changes

include/containers/bitset.h, src/containers/bitset.c
I'm not directly pushing this one in master due to the merge-mess it might create with pending commits on local repos, @lemire I'll wait for your ok before merging this.
It compiles and passes tests for both AVX and NONAVX versions.
=> Cleanup code by uniformizing names

benchmarks/real_bitmaps_benchmark.c, include/bitset_util.h, include/containers/array.h, include/containers/bitset.h, include/containers/containers.h, include/containers/mixed_intersection.h, include/containers/mixed_union.h, include/containers/run.h, include/portability.h, include/roaring.h, include/roaring_array.h, include/roaring_types.h, src/containers/array.c, src/containers/bitset.c, src/containers/containers.c, src/containers/run.c, src/roaring.c, src/roaring_array.c, tests/toplevel_unit.c
Hi all, I have implemented serialisation/deserialisation in the roaring bitmap. Please review the code and hopefully merge it. Thank you.
=> Added serialization/deserialization functions

include/roaring/portability.h
Improving Windows support re: #46
=> Added mingw32's aligned malloc

include/roaring/array_util.h, src/array_util.c, src/bitset_util.c
Some Visual Studio warnings in the SIMD path
=> Removed the causes of some Visual Studio warnings

cpp/roaring.hh, cpp/roaring64map.hh, tests/cpp_unit.cpp
Since C++ lib is compiled with -std=c++11 flag, I suppose that using features introduced by C++11 is OK. :)
=> Added move constructors

src/containers/mixed_equal.c
This PR implements optimization from #99. I didn't add any new unit test, as existing tests already cover the changed function.
=> Improved equality of run and array containers

src/roaring_array.c
=> removed debug line

src/roaring.c, tests/toplevel_unit.c
https://github.com/RoaringBitmap/CRoaring/issues/156
=> Fixed segfault in add_range() when copy_on_write

cpp/roaring64map.hh
=> Silence Visual Studio 2017 warning on std::accumulate()

CMakeLists.txt, benchmarks/array_container_benchmark.c, benchmarks/benchmark.h, benchmarks/bitset_container_benchmark.c, benchmarks/equals_benchmark.c, benchmarks/run_container_benchmark.c, include/roaring/portability.h, src/containers/bitset.c, tests/bitset_container_unit.c, tools/cmake/FindOptions.cmake
* Parallel computation of cardinality in
bitset_compute_cardinality() and logical operations
* Use clock_gettime() for time measuring on non-x64 Linux
(same as clock() but provides better resolution)
=> Optimized some bitset operations for NEON

cpp/roaring64map.hh, tests/cpp_unit.cpp
false && everything == false, so false -> true.
=> fix the 'false' with logical and bug.

cpp/roaring.hh, include/roaring/roaring.h
Fixes https://github.com/RoaringBitmap/CRoaring/issues/223
=> Documenting issue 223.

cpp/roaring64map.hh
1. add copy constructor to Roaring64Map to make gcc9 above no-warnings.
2. re-format code’s indent
=> add copy constructor to roaring64map

include/roaring/containers/containers.h, include/roaring/containers/convert.h, src/containers/convert.c, tests/toplevel_unit.c
Fixing https://github.com/RoaringBitmap/CRoaring/issues/245
=> Fixing issue 245.

src/roaring_array.c
https://github.com/RoaringBitmap/CRoaring/issues/256
=> realloc() commented-out-code moved to issue

cpp/roaring64map.hh
This helps resolve !=/== ambiguity.
=> Fix iterator constness methods.

benchmarks/create_benchmark.c
same as https://github.com/RoaringBitmap/CRoaring/commit/f85a6e93976a6c1e3b5710aed9ad9b3d6ff3a433
=> Missing one more spot for possible build error

include/roaring/roaring.h, src/roaring.c, tests/toplevel_unit.c
=> Implement roaring_bitmap_intersect_with_range

cpp/roaring64map.hh, tests/cpp_unit.cpp
Fixes https://github.com/RoaringBitmap/CRoaring/issues/304
=> Fix and verification for issue 304.

src/roaring.c
=> fixing #325: remove extern statement for roaring_bitmap_contains defined locally

.github/workflows/alpine.yml, .github/workflows/macos-ci.yml, .github/workflows/ubuntu-ci.yml
=> This adds more debug testing.

src/containers/mixed_xor.c
This should also fix #328 (thus the branch name).
=> Actually perform bitset-bitset ixor in place

include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, include/roaring/containers/run.h, include/roaring/roaring.h, src/containers/array.c, src/containers/bitset.c, src/containers/run.c, src/roaring.c, tests/CMakeLists.txt, tests/add_offset.c
For #186 and #144.
It's still a work in progress. It's close to finished but I still need to sort out some bugs in the bitset implementation and clean up the tests, which are currently a bit of a mess and don't really convey enough information on failure.
UPDATE: ready for review.
=> Implement shift operations

README.md, amalgamation.sh, cpp/roaring.hh, include/roaring/memory.h, include/roaring/portability.h, include/roaring/roaring.h, src/CMakeLists.txt, src/containers/array.c, src/containers/bitset.c, src/containers/containers.c, src/containers/run.c, src/memory.c, src/roaring.c, src/roaring_array.c, src/roaring_priority_queue.c, tests/cpp_unit.cpp, tests/toplevel_unit.c
Hi guys, 
Found the discussion in #284 and this is a lightweight implementation of customized allocator. 
We try to use it in our project and it works.
For general users, default allocator would be used. For other users, allocator could be defined.
=> support customized memory hook

README.md, include/roaring/memory.h, src/memory.c
=> Change exports from memory.h to share the common roaring_ prefix

.github/workflows/macos-ci.yml, .github/workflows/ubuntu-18-ci.yml, .github/workflows/ubuntu-ci.yml, .github/workflows/ubuntu-gcc10-ci.yml, .github/workflows/ubuntu-legacy-ci.yml, .github/workflows/ubuntu-noexcept-ci.yml, .github/workflows/ubuntu-oldclang-18-ci.yml, .github/workflows/ubuntu-sani-ci.yml, .github/workflows/vs17-arm-ci.yml, .github/workflows/vs17-ci.yml, .github/workflows/vs17-clang-ci.yml, CMakeLists.txt, benchmarks/array_container_benchmark.c, benchmarks/bitset_container_benchmark.c, benchmarks/run_container_benchmark.c, include/roaring/containers/container_defs.h, include/roaring/isadetection.h, include/roaring/misc/configreport.h, include/roaring/portability.h, include/roaring/utilasm.h, src/roaring_array.c, tests/add_offset.c, tests/mixed_container_unit.c
=> Fixes for clangcl

cpp/roaring.hh, cpp/roaring64map.hh, tests/cpp_unit.cpp
See commit messages for more details
=> Misc cpp fixes

src/roaring.c, tests/cpp_unit.cpp
* Fix a bug that triggered an assert in contains range
* Add a unit test for the scenario that triggered the assert
=> Fix a bug in containsRange that triggered an assert

cpp/roaring64map.hh
Both https://github.com/RoaringBitmap/CRoaring/pull/397 and https://github.com/RoaringBitmap/CRoaring/pull/402 contained identical definitions of `Roaring64Map::ensureRangePopulated()` because they each needed it.
However, once merged into 'master' we should have kept one copy and deleted the other.
=> Fix build: remove duplicate 'ensureRangePopulated()'

amalgamation.sh, benchmarks/array_container_benchmark.c, benchmarks/bitset_container_benchmark.c, benchmarks/run_container_benchmark.c, include/roaring/containers/array.h, include/roaring/containers/bitset.h, include/roaring/containers/containers.h, include/roaring/containers/run.h, include/roaring/isadetection.h, include/roaring/misc/configreport.h, include/roaring/portability.h, src/containers/array.c, src/containers/bitset.c, src/containers/run.c, tests/add_offset.c, tests/bitset_container_unit.c, tests/c_example1.c, tests/cpp_example2.cpp, tests/cpp_random_unit.cpp, tests/mixed_container_unit.c, tests/realdata_unit.c, tests/roaring64map_checked.hh, tests/roaring_checked.hh, tests/run_container_unit.c
Preparing a maintenance release. Mostly just removing unused code.
=> Minor cleaning

include/roaring/containers/containers.h, tests/toplevel_unit.c
Surprising that we have not caught this much earlier. :-(
Fixes https://github.com/RoaringBitmap/CRoaring/issues/429
=> Fix memory leak.

src/containers/mixed_subset.c, tests/toplevel_unit.c
Fixes https://github.com/RoaringBitmap/CRoaring/issues/431
=> Verifying and testing issue 431.

include/roaring/containers/containers.h, tests/toplevel_unit.c
It is a single character missing !!!
Fix https://github.com/RoaringBitmap/CRoaring/issues/433
=> Fix for issue 433

include/roaring/containers/containers.h, tests/toplevel_unit.c
Credit to @Dr-Emann  for demonstrating the bug.
=> Verifies and fixes issue 436

src/roaring.c, tests/toplevel_unit.c
Fixes https://github.com/RoaringBitmap/CRoaring/issues/440
=> Verifying and fixing issue 440.

fuzz/build.sh, fuzz/croaring_fuzzer.c, fuzz/croaring_fuzzer.options, fuzz/croaring_fuzzer_cc.cc
This change will make future changes/additions to fuzz harnesses easier, without needing approvals from the OSS-fuzz team.
=> fuzz: Moves fuzz harnesses from oss-fuzz to CRoaring

cpp/roaring.hh, fuzz/croaring_fuzzer_cc.cc
This PR also improves the C++ documentation.
=> fix:an error with the fuzzer

.github/workflows/alpine.yml, .github/workflows/cifuzz.yml, .github/workflows/codeql.yml, .github/workflows/documentation.yml, .github/workflows/macos-ci.yml, .github/workflows/s390x.yml, .github/workflows/ubuntu-18-ci.yml, .github/workflows/ubuntu-ci.yml, .github/workflows/ubuntu-debug-sani-ci.yml, .github/workflows/ubuntu-gcc10-ci.yml, .github/workflows/ubuntu-legacy-ci.yml, .github/workflows/ubuntu-noexcept-ci.yml, .github/workflows/ubuntu-oldclang-18-ci.yml, .github/workflows/ubuntu-sani-ci.yml, .github/workflows/vs16-arm-ci.yml, .github/workflows/vs16-ci.yml, .github/workflows/vs17-arm-ci.yml, .github/workflows/vs17-ci.yml, .github/workflows/vs17-clang-ci.yml
Closes https://github.com/RoaringBitmap/CRoaring/issues/447
=> Set minimum permissions to workflows

README.md, include/roaring/bitset_util.h, include/roaring/isadetection.h, include/roaring/misc/configreport.h, include/roaring/portability.h, src/array_util.c, src/bitset_util.c, src/containers/array.c, src/containers/bitset.c, src/containers/convert.c, src/containers/run.c, tools/cmake/FindOptions.cmake
I just did some minor tweaks but no actual difficult work. 
Built on top of https://github.com/RoaringBitmap/CRoaring/pull/446
Work by hui han([hui.han@intel.com](mailto:hui.han@intel.com))
Signed-off-by: lifan lin([lifan.lin@intel.com](mailto:lifan.lin@intel.com))
=> add avx512 support

include/roaring/array_util.h
=> type fix: greater/less then -> greater/less than

tests/array_container_unit.c
Attempts to verify https://github.com/RoaringBitmap/CRoaring/issues/476#issuecomment-1550798276
=> Additional tests related to issue 476

include/roaring/portability.h
Verifying and fixing issue https://github.com/RoaringBitmap/CRoaring/issues/484
=> Fixing issue 484

.github/workflows/scorecard.yml
Resolves https://github.com/RoaringBitmap/CRoaring/issues/521
=> Flagging supply-chain security issues

tests/toplevel_unit.c
I think that issue 538 was fixed by @longqimin in https://github.com/RoaringBitmap/CRoaring/pull/537 but this adds a verification.
Fixes https://github.com/RoaringBitmap/CRoaring/issues/538
=> Trying to verify issue 538

src/roaring64.c
Fixed some compilation warnings
=> Warning fix

README.md
Before submitting this PR, run `tools/clang-format.sh` on your changes. See the "Contributing" section in the README for details.
=> Update README.md about running microbenchmarks

README.md
Updated README with new conan instructions
=> Update README.md with up2date conan instructions

benchmarks/containsmulti_benchmark.c, include/roaring/bitset/bitset.h, src/bitset.c, tests/cbitset_unit.c
Fixes https://github.com/RoaringBitmap/CRoaring/issues/666
=> fix issue 666

.github/workflows/s390x.yml, src/art/art.c, src/roaring64.c
Fixes https://github.com/RoaringBitmap/CRoaring/issues/680
=> fix issue 680

include/roaring/portability.h
Fixes  https://github.com/RoaringBitmap/CRoaring/issues/690
=> let us try removing _XOPEN_SOURCE

README.md, src/containers/run.c, tests/toplevel_unit.c
Fixes https://github.com/RoaringBitmap/CRoaring/issues/704
=> better doc

README.md
This is cross-compile guide of using the CRoaring in OpenHarmony, so we'd like to contribute it. Hope it will help the developers.
=> Adding OpenHarmony Cross-Compile guide into README.md

src/containers/run.c
=> run_container_cardinality + AVX-512 does not seem useful.
